// maybe change to prounoun.eso or conjunction.y conjuction.que
"use client"

import { Female } from "@mui/icons-material"
import { data } from "autoprefixer"

const words = {
	artcl: {
		info: [],
		el: {
			translations: ["the (M)"],
			word: "el",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=the&tl=es&total=1&idx=0&textlen=3",
			pos: "Article",
			gender: "masculine",
		},
		la: {
			translations: ["the (F)"],
			word: "la",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=the&tl=es&total=1&idx=0&textlen=3",
			pos: "Article",
			gender: "feminine",
		},
	},
	conj: {
		info: [
			"CONJUNCTIONS don't pass the FOOD or the EAT test they are something New!",
			"CONJUNCTIONS are Connecting Words which hold a sentence, or even multiple sentences together!",
			"Proper Spanish entence can ONLY have ONE verb! (EATS EAT or ATE (NOT EATING/EATEN(Those are Nouns sorta!))), conjunctions allow combining phrases/sentences",
		],
		que: {
			translations: ["that"],
			word: "que",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=that&tl=es&total=1&idx=0&textlen=4",
			pos: "Conjunction",
			info: [
				"Que is the NUMBER 1 Word in Spanish, but English THAT is not even in the Top 5, why is that? In Spanish if you CAN use Que as a connector then you MUST. Where in English we can say things like 'We hope we get there soon!' In spanish you would have to say 'We hope THAT we get there soon!'",

				"If you CAN add QUE/that in Spanish as a connector then you HAVE to!",
			],
		},
		y: {
			translations: ["and"],
			word: "y",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=and&tl=es&total=1&idx=0&textlen=3",
			pos: "Conjunction",
			info: ["Y is a direct translation of AND"],
		},
	},

	pron: {
		info: ["PRONOUNS are INTERCHANGEABLE with NOUNS!"],
		eso: {
			translations: ["that"],
			word: "eso",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=that&tl=es&total=1&idx=0&textlen=4",
			pos: "Pronoun",
			info: [
				"ESO is likely the MOST VERSATILE word in Spanish! It is interchangeable with any NOUN or NOUN PHRASE, it can also represent actions and concepts",
			],
		},
	},
	prep: {
		info: [
			"PREPOSITIONS are ALWAYS used directly before a NOUN of some type, that's why they are call PRE-POSITIONS!",
		],
		de: {
			translations: ["from", "of"],
			word: "de",
			pos: "Preposition",
			info: [
				"De  is mostly used as OF as in one of these three ideas:\nORIGIN: 'The people OF the north!', or\nPOSSESION: 'The house OF my parents', or\nMATERIAL: 'The sheet OF paper'",
				"ORIGIN: In english we say Sydney is a City in Australia, but Spanish would say Sydney is a city OF or DE Autralia. Other examples include: 'The birds of Africa', 'The wind from the cellar' 'My friend from Toronto', 'The largest cities of Columbia'",
				"POSSESION: English says 'My friends father' but spanish would say 'The father OF my friend!' other examples include: 'The cap of the bottle', 'the door of the house' and 'the hand of the writer'",
				"POSSESTION2: English uses Contractions like 'The bottle's cap' but Spanish DOESN'T have this! You need to change the order and use DE",
				"MATERIAL: The Statue of Bronze. The Table of Stone. The horse of wood. ETC!",
			],
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=from&tl=es&total=1&idx=0&textlen=4",
		},
		a: {
			translations: ["to"],
			word: "a",
			pos: "Preposition",
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=to&tl=es&total=1&idx=0&textlen=2",
		},
	},
	advrb: {
		info: [
			"Adverbs can go anywhere in a sentence and mean all kinds of things!",
		],

		no: {
			translations: ["not", "no"],
			word: "no",
			pos: "Adverb",
			info: [
				"NO means NOT moreso than NO!",
				"Most Adverbs can go anywhere in a sentence and mean all kinds of things, but NO is far more strict, used very specifically to NEGATE a sentence.",
				"In English we can use contractions but they don't exist in Spanish, so we have to use NOT/NO!",
				"When translating English to Spanish and dealing with Contractions (Can't, Don't, Won't) Simply UNTIE the NOT! Turning Can't into Can not!",
				"In Spanish verb types like CAN BE have to stick together, and the adverb NO must go first!",
				"In Spanish DO HAVE isn't a real concept, we remove the word DO: I Don't Have that! = I no have that. 'Untie the Knot, and make the D Disappear!'",
				"There are no contraction in Spanish. For verb types like Can't: Untie the NOT, then move it to front: NO CAN BE!",
				"There are no contractions and also no concept for DO or DID (Do have, do say, do whatever) in Spanish. Untie the NOT, and make the Do DISAPPEAR!",
				"You might think NO should work like 'She can NO be' but adverbs don't work like this. Verb Structures like CAN BE have to stick together, and the adverb has to go first!",
			],
			audio:
				"https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=no&tl=es&total=1&idx=0&textlen=3",
		},
	},
	noun: {
		info: [
			"FOOD TEST: Nouns in Spanish function as any WORD or PHRASE that can be substituted for the word FOOD!",
			"NOUNS aren't just PEOPLE, PLACES, or THINGS, they can also be ACTIONS! Such as: I enjoy LOSING MYSELF IN A NEW CITY",
			"EVERY Noun in Spanish is either Masculine or Feminine.",
		],
	},
	verb: {
		info: [
			"EAT TEST: Verbs are any word that can be replaced by EAT, EATS or ATE!",
			"What about EATING? EATING or EATEN actually don't behave as verbs in the EAT test! EATING is my Favority activiy, EATING is the NOUN!",
			"Proper Spanish sentence can ONLY have ONE verb! (EATS EAT or ATE (NOT EATING/EATEN(Those are Nouns sorta!))), conjunctions allow combining phrases/sentences",
			"VERB PHRASES are where multiple verbs are functioning as only one verb! 'I want to have more!' looks like two verbs, WANT and HAVE but it counts as one! 'I will continue eating my food' Three verbs which counts as ONE! you could change it to 'I EAT my food'",
		],
	},

	dObj: {
		info: [
			`If a pronoun is interchangeable with "him", it's probably a direct object pronoun. "We found it!" We found HIM`,
			`PLACEMENT: Whenever a DIRECT OBJECT PRONOUN occurs in Spanish, it ALWAYS occurs DIRECTLY before the verb. We found him = We HIM found, or We LO found.`,
			` Spanish speakers don't say "I hugged him." Instead, they say "I him hugged." And they don't say "I brought her." They say "I her brought." And instead of "I did it", they say "I it did."`,
			`When NO and LO are together: The Direct Object Pronoun is most important to be next to the verb.`,
		],
		lo: {
			translations: ["him", "it (M)"],
			word: "lo",
			pos: "Direct Object Pronoun",
			gender: "masculine",
		},
		la: {
			translations: ["her", "it (F)"],
			word: "la",
			pos: "Direct Object Pronoun",
			gender: "feminine",
		},
	},
}

const { conj, pron, prep, advrb, noun, verb, artcl, dObj } = words

const sideLessonPotential = [
	{
		lesson: 1,
		info: "general intro, info",
	},
	{
		lesson: 2,
		info: "FOOD test, EAT test, Potato head game.",
	},
	{
		lesson: 6,
		info: "Find the direct object",
	},
]

const spanishData = {
	lessons: {
		3: {
			lesson: 3,
			name: "Lesson 3",
			details: "Conjunctions (Y and QUE) and ESO",
			info: [
				noun.info[1],
				noun.info[0],
				verb.info[0],
				verb.info[1],
				verb.info[2],
				conj.info[0],
				conj.info[1],
				conj.que.info[0],
				conj.que.info[1],
				verb.info[3],
				pron.eso.info[0],
				conj.y.info[0],
			],
			wordBank: [conj.y, pron.eso, conj.que],
			sentences: [
				{
					id: 1,
					sentence: "She and I want that",
					translation: "She Y I want ESO",
					data: [
						{ word: "She" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{ word: "want" },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 2,
					reference: { que: [conj.que.info[1]] },
					sentence: "We said that was fine",
					translation: "We said QUE ESO was fine",
					data: [
						{
							phrase: "We said",
							translation: conj.que,
							phraseTranslation: "We said QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "that", translation: pron.eso },
						{ word: "was" },
						{ word: "fine" },
					],
				},
				{
					id: 3,
					sentence: "I hope that that is OK",
					translation: "I hope QUE ESO is OK",
					data: [
						{ word: "I" },
						{ word: "hope" },
						{ word: "that", translation: conj.que },
						{ word: "that", translation: pron.eso },
						{ word: "is" },
						{ word: "OK" },
					],
				},
				{
					id: 4,
					sentence: "People say that it's good",
					translation: "People say QUE its good",
					data: [
						{ word: "People" },
						{ word: "say" },
						{ word: "that", translation: conj.que },
						{ word: "it's" },
						{ word: "good" },
					],
				},
				{
					id: 5,
					sentence: "We said that that was fine!",
					translation: "We said QUE ESO was fine!",
					data: [
						{ word: "We" },
						{ word: "said" },
						{ word: "that", translation: conj.que },
						{ word: "that", translation: pron.eso },
						{ word: "was" },
						{ word: "fine" },
					],
				},
				{
					id: 6,
					reference: { que: [conj.que.info[1]] },
					sentence: "I told them that was in the way",
					translation: "I told them QUE ESO was in the way",
					data: [
						{
							phrase: "I told them",
							translation: conj.que,
							phraseTranslation: "I told them QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "that", translation: pron.eso },
						{ word: "was" },
						{ word: "in" },
						{ word: "the" },
						{ word: "way" },
					],
				},
				{
					id: 7,
					reference: { que: [conj.que.info[1]] },
					sentence: "I hope he gets that soon",
					translation: "I hope QUE he gets ESO soon",
					data: [
						{
							phrase: "I hope",
							translation: conj.que,
							phraseTranslation: "I hope QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "he" },
						{ word: "gets" },
						{ word: "that", translation: pron.eso },
						{ word: "soon" },
					],
				},
				{
					id: 8,
					sentence: "I don't want that here!",
					translation: "I don't want ESO here!",
					data: [
						{ word: "I" },
						{ word: "don't" },
						{ word: "want" },
						{ word: "that", translation: pron.eso },
						{ word: "here" },
					],
				},
				{
					id: 9,
					reference: { que: [conj.que.info[1]] },
					sentence: "He said they said that!",
					translation: "He said QUE they said ESO!",
					data: [
						{
							phrase: "He said",
							translation: conj.que,
							phraseTranslation: "He said QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "they" },
						{ word: "said" },
						{ word: "that!", translation: pron.eso },
					],
				},
				{
					id: 10,
					sentence: "I said this and she said that",
					translation: "I said this Y she said ESO",
					data: [
						{ word: "I" },
						{ word: "said" },
						{ word: "this" },
						{ word: "and", translation: conj.y },
						{ word: "she" },
						{ word: "said" },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 11,
					sentence: "They found that?",
					translation: "They found ESO?",
					data: [
						{ word: "They" },
						{ word: "found" },
						{ word: "that?", translation: pron.eso },
					],
				},
				{
					id: 12,
					sentence: "That isn't my favorite thing",
					translation: "ESO NO is my favorite thing",
					data: [
						{ word: "That", translation: pron.eso },
						{ word: "isn't my favorite thing" },
					],
				},
				{
					id: 13,
					sentence: "I told him that we arrived",
					translation: "I told him QUE we arrived",
					data: [
						{ phrase: "I told him" },
						{ word: "that", translation: conj.que },
						{ word: "we" },
						{ word: "arrived" },
					],
				},
				{
					id: 14,
					sentence: "I hope that you have a nice day",
					translation: "I hope QUE you have a nice day",
					data: [
						{ phrase: "I hope" },
						{ word: "that", translation: conj.que },
						{ word: "you" },
						{ word: "have" },
						{ word: "a" },
						{ word: "nice" },
						{ word: "day" },
					],
				},
				{
					id: 15,
					sentence: "We want that as soon as possible",
					translation: "We want ESO as soon as possible",
					data: [
						{ word: "We" },
						{ word: "want" },
						{ word: "that", translation: pron.eso },
						{ word: "as soon as possible" },
					],
				},
				{
					id: 16,
					sentence: "They told me that that was impossible",
					translation: "They told me QUE ESO was impossible",
					data: [
						{ word: "They" },
						{ word: "told" },
						{ word: "me" },
						{ word: "that", translation: conj.que },
						{ word: "that", translation: pron.eso },
						{ word: "was" },
						{ word: "impossible" },
					],
				},
				{
					id: 17,
					sentence: "I dreamed that I was back in highschool",
					translation: "I dreamed QUE I was back in highschool",
					data: [
						{ word: "I" },
						{ word: "dreamed" },
						{ word: "that", translation: conj.que },
						{ word: "I" },
						{ word: "was" },
						{ word: "back" },
						{ word: "in" },
						{ word: "highschool" },
					],
				},
				{
					id: 18,
					reference: { que: [conj.que.info[1]] },
					sentence: "I hope he told you he was here",
					translation: "I hope QUE he told you QUE he was here",
					data: [
						{
							phrase: "I hope",
							translation: conj.que,
							phraseTranslation: "I hope QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{
							phrase: "he told you",
							translation: conj.que,
							phraseTranslation: "he told you QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ phrase: "he was here" },
					],
				},
			],
		},
		4: {
			lesson: 4,
			name: "Lesson 4",
			details: "Prepositions: DE and A, Adverb NO ",
			info: [
				"De and A are very common prepositions, meaning of or from, and to",
				prep.info[0],
				prep.de.info[0],
				"No is an ADVERB",
				advrb.no.info[0],
				advrb.no.info[1],
				advrb.no.info[2],
				advrb.no.info[3],
				advrb.no.info[8],
				advrb.no.info[5],
			],
			wordBank: [advrb.no, prep.de, prep.a],
			sentences: [
				{
					id: 1,
					reference: { no: [advrb.no.info[6]] },
					sentence: "She can't be at the house",
					translation: "She NO can be at the house",
					data: [
						{ word: "She" },
						{
							phrase: "Can't be",
							translation: advrb.no,
							phraseTranslation: "NO can be",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "at" },
						{ word: "the" },
						{ word: "house" },
					],
				},
				{
					id: 2,
					reference: { no: [advrb.no.info[7]], que: [conj.que.info[1]] },
					sentence: "Don't say you're not here",
					translation: "NO say QUE you NO are here",
					data: [
						{
							phrase: "Don't say",
							translation: [advrb.no, conj.que],
							phraseTranslation: "NO say QUE",
							reference: { no: [advrb.no.info[7]], que: [conj.que.info[1]] },
						},
						{
							phrase: "you're not",
							translation: advrb.no,
							phraseTranslation: "you NO are",
						},
						{ word: "here" },
					],
				},
				{
					id: 3,
					reference: { no: [advrb.no.info[7]] },
					sentence: "We didn't go to this store",
					translation: "We NO went A this store",
					data: [
						{ word: "We" },
						{
							phrase: "didn't go",
							translation: advrb.no,
							phraseTranslation: "NO went",
							reference: { no: [advrb.no.info[7]] },
						},
						{ word: "to", translation: prep.a },
						{ word: "this" },
						{ word: "store" },
					],
				},
				{
					id: 4,
					reference: { no: [advrb.no.info[6]] },
					sentence: "She won't send that to her sister",
					translation: "She NO will send ESO A her sister",
					data: [
						{ word: "She" },
						{
							phrase: "won't send",
							translation: advrb.no,
							phraseTranslation: "NO will send",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "that", translation: pron.eso },
						{ word: "to", translation: prep.a },
						{ word: "her" },
						{ word: "sister" },
					],
				},
				{
					id: 5,
					sentence: "Are you tired of doing that?",
					translation: "Are you tired DE doing QUE ESO?",
					data: [
						{ word: "Are" },
						{ word: "you" },
						{ word: "tired" },
						{ word: "of", translation: prep.de },
						{ word: "doing" },
						{ word: "that?", translation: pron.eso },
					],
				},
				{
					id: 6,
					reference: { no: [advrb.no.info[6]] },
					sentence: "This isn't your stuff",
					translation: "This NO is your stuff",
					data: [
						{ word: "This" },
						{
							phrase: "isn't",
							translation: advrb.no,
							phraseTranslation: "NO is",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "your" },
						{ word: "stuff" },
					],
				},
				{
					id: 7,
					reference: { no: [advrb.no.info[6]] },
					sentence: "We can't do that",
					translation: "We NO can do ESO",
					data: [
						{ word: "We" },
						{
							phrase: "can't do",
							translation: advrb.no,
							phraseTranslation: "NO can do",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 8,
					sentence: "He and I drove from this place",
					translation: "He Y I drove DE this place",
					data: [
						{ word: "He" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{ word: "drove" },
						{ word: "from", translation: prep.de },
						{ word: "this" },
						{ word: "place" },
					],
				},
				{
					id: 9,
					reference: { no: [advrb.no.info[6]] },
					sentence: "I can't have more of that",
					translation: "I NO can have more of ESO",
					data: [
						{ word: "I" },
						{
							phrase: "can't have",
							translation: advrb.no,
							phraseTranslation: "NO can have",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "more" },
						{ word: "of" },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 10,
					sentence: "My friend was from another state",
					translation: "My friend was DE another state",
					data: [
						{ word: "My" },
						{ word: "friend" },
						{ word: "was" },
						{ word: "from", translation: prep.de },
						{ word: "another" },
						{ word: "state" },
					],
				},
				{
					id: 11,
					reference: { no: [advrb.no.info[6]], que: [conj.que.info[1]] },
					sentence: "We won't say you have that",
					translation: "We NO will say QUE you have ESO",
					data: [
						{ word: "We" },
						{
							phrase: "won't say",
							translation: [advrb.no],
							phraseTranslation: "NO will say",
							reference: { no: [advrb.no.info[6]] },
						},
						{
							word: "you have",
							translation: conj.que,
							phraseTranslation: "QUE you have",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 12,
					reference: { no: [advrb.no.info[7]] },
					sentence: "She doesn't have that",
					translation: "She NO has ESO",
					data: [
						{ word: "She" },
						{
							phrase: "doesn't have",
							translation: advrb.no,
							phraseTranslation: "NO has",
							reference: { no: [advrb.no.info[7]] },
						},
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 13,
					reference: { no: [advrb.no.info[7]], que: [conj.que.info[1]] },
					sentence: "This doesn't tell us that is done",
					translation: "This NO tells us QUE ESO is done",
					data: [
						{ word: "This" },
						{
							phrase: "doesn't tell",
							translation: advrb.no,
							phraseTranslation: "NO tells",
							reference: { no: [advrb.no.info[7]] },
						},
						{
							phrase: "us that",
							translation: conj.que,
							phraseTranslation: "us QUE",
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "is" },
						{ word: "done" },
					],
				},
				{
					id: 14,
					sentence: "Give my brother more of that",
					translation: "Give my brother more DE ESO",
					data: [
						{ word: "Give" },
						{ word: "my" },
						{ word: "brother" },
						{ word: "more" },
						{ word: "of", translation: prep.de },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 15,
					sentence: "It came down from the mountain",
					translation: "It came down DE the mountain",
					data: [
						{ word: "It" },
						{ word: "came" },
						{ word: "down" },
						{ word: "from", translation: prep.de },
						{ word: "the" },
						{ word: "mountain" },
					],
				},
				{
					id: 16,
					sentence: "I'm tired of waiting around like this",
					translation: "I'm tired DE waiting around like this",
					data: [
						{ word: "I'm tired" },
						{ word: "of", translation: prep.de },
						{ phrase: "waiting around like this" },
					],
				},
				{
					id: 17,
					sentence: "The girl went to another country",
					translation: "The girl went A another country",
					data: [
						{ word: "The girl went" },
						{ word: "to", translation: prep.a },
						{ word: "another" },
						{ word: "country" },
					],
				},
				{
					id: 18,
					sentence: "I want to give that to my brother",
					translation: "I want to give ESO A my brother",
					data: [
						{ word: "I" },
						{ word: "want" },
						{ word: "to" },
						{ word: "give" },
						{ word: "that", translation: pron.eso },
						{ word: "to", translation: prep.a },
						{ word: "my" },
						{ word: "brother" },
					],
				},
				{
					id: 19,
					sentence: "Mark goes from New York to Houston",
					translation: "Mark goes DE New York A Houston",
					data: [
						{ word: "Mark" },
						{ word: "goes" },
						{ word: "from", translation: prep.de },
						{ word: "New" },
						{ word: "York" },
						{ word: "to", translation: prep.a },
						{ word: "Houston" },
					],
				},
				{
					id: 20,
					reference: { no: [advrb.no.info[6]] },
					sentence: "This isn't my house",
					translation: "This NO is my house",
					data: [
						{ word: "This" },
						{
							phrase: "isn't",
							translation: advrb.no,
							phraseTranslation: "NO is",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "my" },
						{ word: "house" },
					],
				},
				{
					id: 21,
					reference: { no: [advrb.no.info[6]] },
					sentence: "She can't walk very fast",
					translation: "She NO can walk very fast",
					data: [
						{ word: "She" },
						{
							phrase: "can't",
							translation: advrb.no,
							phraseTranslation: "NO can",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "walk" },
						{ word: "very" },
						{ word: "fast" },
					],
				},
				{
					id: 22,
					reference: { no: [advrb.no.info[7]] },
					sentence: "They don't see why",
					translation: "They NO see why",
					data: [
						{ word: "They" },
						{
							phrase: "don't see",
							translation: advrb.no,
							phraseTranslation: "NO see",
							reference: { no: [advrb.no.info[7]] },
						},
						{ word: "why" },
					],
				},
				{
					id: 23,
					reference: { no: [advrb.no.info[6]] },

					sentence: "That won't matter",
					translation: "ESO NO will matter",
					data: [
						{ word: "That", translation: pron.eso },
						{
							phrase: "won't mattter",
							translation: advrb.no,
							phraseTranslation: "NO will matter",
							reference: { no: [advrb.no.info[6]] },
						},
					],
				},
				{
					id: 24,
					reference: { no: [advrb.no.info[7]] },
					sentence: "This doesn't tell us much",
					translation: "This NO tells us much",
					data: [
						{ word: "This" },
						{
							phrase: "doesn't tell",
							translation: advrb.no,
							phraseTranslation: "NO tells",
							reference: { no: [advrb.no.info[7]] },
						},
						{ word: "us" },
						{ word: "much" },
					],
				},
				{
					id: 25,
					reference: { no: [advrb.no.info[7]] },
					sentence: "He didn't know",
					translation: "He NO knew",
					data: [
						{ word: "He" },
						{
							phrase: "didn't know",
							translation: advrb.no,
							phraseTranslation: "NO knew",
							reference: { no: [advrb.no.info[7]] },
						},
					],
				},
			],
		},
		5: {
			lesson: 5,
			name: "Lesson 5",
			details: "Three common uses of DE!",
			info: [
				"From or Of only covers about half of the uses of DE! Because prepositions are notorious for use in quirky context. There are THREE main uses of DE as OF:",
				prep.de.info[1],
				prep.de.info[2],
				prep.de.info[3],
				prep.de.info[4],
			],
			sentences: [
				{
					id: 1,
					reference: { de: [prep.de.info[2], prep.de.info[4]] },
					sentence: "It's Samuel's water bottle!",
					translation: "It's the bottle DE water DE Samuel",
					data: [
						{ word: "It's" },
						{
							phrase: "Samuel's water bottle",
							phraseTranslation: "the bottle DE water DE Samuel",
							translation: [prep.de, prep.de],
							reference: { de: [prep.de.info[2], prep.de.info[4]] },
						},
					],
				},
				{
					id: 2,
					reference: { no: [advrb.no.info[6]], que: [conj.que.info[1]] },
					sentence: "You won't tell me they did it?",
					translation: "You NO will tell QUE they did it?",
					data: [
						{ word: "You" },
						{
							phrase: "won't tell",
							translation: advrb.no,
							phraseTranslation: "NO will tell",
							reference: { no: [advrb.no.info[6]] },
						},
						{ word: "me" },
						{
							phrase: "they did it?",
							phraseTranslation: "QUE they did it",
							translation: conj.que,
							reference: { que: [conj.que.info[1]] },
						},
					],
				},
				{
					id: 3,
					reference: {
						no: [advrb.no.info[7]],
						prep: [prep.de.info[2], prep.de.info[4]],
					},
					sentence: "Don't touch John's wine glass",
					translation: "NO touch the glass DE wine DE John",
					data: [
						{
							phrase: "Don't touch",
							translation: advrb.no,
							phraseTranslation: "NO touch",
							reference: { no: [advrb.no.info[7]] },
						},
						{
							phrase: "John's wine glass",
							phraseTranslation: "the glass DE wine DE John",
							translation: prep.de,
							reference: { prep: [prep.de.info[2], prep.de.info[4]] },
						},
					],
				},
				{
					id: 4,
					sentence: "They took it to the lady from Italy",
					translation: "They took it A the lady DE Italy",
					data: [
						{ phrase: "They took it" },
						{ word: "to", translation: prep.a },
						{ phrase: "the lady" },
						{ word: "from", translation: prep.de },
						{ word: "Italy" },
					],
				},
				{
					id: 5,
					reference: { no: [advrb.no.info[6]] },
					sentence: "This can't be from from Spain!",
					translation: "This NO can be DE Spain!",
					data: [
						{ word: "This" },
						{
							phrase: "can't be",
							translation: advrb.no,
							phraseTranslation: "NO can be",
						},
						{ word: "from", translation: prep.de },
						{ word: "Spain!" },
					],
				},
				{
					id: 6,
					reference: { de: [prep.de.info[4]] },
					sentence: "I saw that it was a ceramic mug",
					translation: "I saw QUE it was a mug DE ceramic",
					data: [
						{ word: "I" },
						{ word: "saw" },
						{
							word: "that",
							translation: conj.que,
						},
						{ word: "it was" },
						{ word: "a" },
						{
							phrase: "ceramic mug",
							phraseTranslation: "mug DE ceramic",
							translation: prep.de,
							reference: { de: [prep.de.info[4]] },
						},
					],
				},
				{
					id: 7,
					reference: { que: [conj.que.info[1]] },
					sentence: "You hoped she and I were together",
					translation: "You hoped QUE she Y I were together",
					data: [
						{
							phrase: "You hoped",
							phraseTranslation: "You hoped QUE",
							translation: conj.que,
							reference: { que: [conj.que.info[1]] },
						},
						{ word: "she" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{ word: "were" },
						{ word: "together" },
					],
				},
				{
					id: 8,
					reference: [advrb.no.info[6]],
					sentence: "I said that it isn't here",
					translation: "I said QUE it NO is here",
					data: [
						{ word: "I" },
						{ word: "said" },
						{
							word: "that",
							translation: conj.que,
						},
						{ word: "it" },
						{
							phrase: "isn't here",
							phraseTranslation: "NO is here",
							translation: advrb.no,
						},
					],
				},
				{
					id: 9,
					reference: [conj.que.info[1], advrb.no.info[6]],
					sentence: "She hoped we woudn't go to Canada",
					translation: "She hoped QUE we NO would go A Canada",
					data: [
						{
							phrase: "She hoped",
							translation: conj.que,
							phraseTranslation: "She hoped QUE",
						},
						{ word: "we" },
						{
							phrase: "woudn't go",
							phraseTranslation: "NO would go",
							translation: advrb.no,
						},
						{ word: "to", translation: prep.a },
						{ word: "Canada" },
					],
				},
				{
					id: 10,
					reference: [advrb.no.info[6]],
					sentence: "I couldn't believe that!",
					translation: "I NO could believe ESO!",
					data: [
						{ word: "I" },
						{
							phrase: "couldn't believe",
							translation: advrb.no,
							phraseTranslation: "NO could believe",
						},
						{ word: "that!", translation: pron.eso },
					],
				},
				{
					id: 11,
					reference: [prep.de.info[4], prep.de.info[2]],
					sentence: "It was Maria's plastic chair",
					translation: "It was the chair DE plastic DE Maria",
					data: [
						{ word: "It" },
						{ word: "was" },
						{
							phrase: "Maria's plastic chair",
							phraseTranslation: "the chair DE plastic DE Maria",
							translation: prep.de,
						},
					],
				},
				{
					id: 12,
					reference: [conj.que.info[1]],
					sentence: "I think he ran from the house",
					translation: "I think QUE he ran DE the house",
					data: [
						{
							phrase: "I think",
							translation: conj.que,
							phraseTranslation: "I think QUE",
						},
						{ word: "he ran" },

						{ word: "from", translation: prep.de },
						{ word: "the house" },
					],
				},
				{
					id: 13,
					reference: [advrb.no.info[7]],
					sentence: "That doesn't matter.",
					translation: "ESO NO matters.",
					data: [
						{ word: "That" },
						{
							phrase: "doesn't matter.",
							phraseTranslation: "NO matters.",
							translation: advrb.no,
						},
					],
				},
				{
					id: 14,
					sentence: "That came from this window",
					translation: "ESO came DE this window",
					data: [
						{ word: "That came" },
						{ word: "from", translation: prep.de },
						{ word: "this window" },
					],
				},
				{
					id: 15,
					reference: [advrb.no.info[7]],
					sentence: "She didn't care and I knew it",
					translation: "She NO cared Y I knew it",
					data: [
						{
							phrase: "She didn't care",
							phraseTranslation: "She NO cared",
							translation: advrb.no,
						},
						{ word: "and", translation: conj.y },
						{ word: "I knew it" },
					],
				},
				{
					id: 16,
					sentence: "The birds of Africa",
					translation: "The birds DE Africa",
					data: [
						{ word: "The" },
						{ word: "birds" },
						{ word: "of", translation: prep.de },
						{ word: "Africa" },
					],
				},
				{
					id: 17,
					sentence: "The special wine from the cellar",
					translation: "The special wine DE the cellar",
					data: [
						{ word: "The" },
						{ word: "special" },
						{ word: "wine" },
						{ word: "from", translation: prep.de },
						{ word: "the cellar" },
					],
				},
				{
					id: 18,
					sentence: "My friend from Toronto",
					translation: "My friend DE Toronto",
					data: [
						{ word: "My friend" },
						{ word: "from", translation: prep.de },
						{ word: "Toronto" },
					],
				},
				{
					id: 19,
					sentence: "The largest cities of Columbia",
					translation: "The largest cities DE Columbia",
					data: [
						{ word: "The" },
						{ word: "largest" },
						{ word: "cities" },
						{ word: "of", translation: prep.de },
						{ word: "Columbia" },
					],
				},
				{
					id: 20,
					sentence: "The pilot's schedule",
					translation: "The schedule DE the pilot",
					data: [
						{ word: "The" },
						{
							phrase: "pilot's schedule",
							translation: prep.de,
							phraseTranslation: "schedule DE the pilot",
						},
					],
				},
				{
					id: 21,
					sentence: "The rich smell of the food",
					translation: "The rich smell DE the food",
					data: [
						{ word: "The" },
						{ word: "rich" },
						{ word: "smell" },
						{ word: "of", translation: prep.de },
						{ word: "the food" },
					],
				},
				{
					id: 22,
					reference: [prep.de.info[3]],
					sentence: "Your brother's foot",
					translation: "The foot DE your brother",
					data: [
						{
							phrase: "Your brother's foot",
							translation: prep.de,
							phraseTranslation: "The foot DE your brother",
						},
					],
				},
				{
					id: 23,
					reference: [prep.de.info[2], prep.de.info[3]],
					sentence: "The doctor's sister's nose",
					translation: "The nose DE the sister DE the doctor",
					data: [
						{
							phrase: "The doctor's sister's nose",
							translation: prep.de,
							phraseTranslation: "The nose DE the sister DE the doctor",
						},
					],
				},
				{
					id: 24,
					reference: [conj.que.info[1]],
					sentence: "I said I was from Arizona",
					translation: "I said QUE I was DE Arizona",
					data: [
						{
							phrase: "I said",
							translation: conj.que,
							phraseTranslation: "I said QUE",
						},
						{ word: "I" },
						{ word: "was" },
						{ word: "from", translation: prep.de },
						{ word: "Arizona" },
					],
				},
				{
					id: 25,
					reference: [
						conj.que.info[1],
						prep.de.info[4],
						prep.de.info[2],
						advrb.no.info[6],
					],
					sentence: "I hope Mom's leather jacket wasn't lost",
					translation: "I hope QUE the jacket DE leather DE Mom NO was lost",
					data: [
						{
							phrase: "I hope",
							translation: conj.que,
							phraseTranslation: "I hope QUE",
						},
						{
							phrase: "Mom's leather jacket",
							translation: prep.de,
							phraseTranslation: "the jacket DE leather DE Mom",
						},
						{
							phrase: "wasn't lost",
							translation: advrb.no,
							phraseTranslation: "NO was lost",
						},
					],
				},
				{
					id: 26,
					reference: [conj.que.info[1], advrb.no.info[6]],
					sentence: "I said it isn't here",
					translation: "I said QUE it NO is here",
					data: [
						{
							phrase: "I said",
							translation: conj.que,
							phraseTranslation: "I said QUE",
						},
						{ word: "it" },
						{
							phrase: "isn't here",
							translation: advrb.no,
							phraseTranslation: "NO is here",
						},
					],
				},
			],
		},
		6: {
			lesson: 6,
			name: "Lesson 6",
			details: "THE! First Articles and Gender",
			info: [
				"Spanish has several words to mean THE, most common is EL for MASC, and LA for FEM",
				noun.info[2],
			],
			wordBank: [artcl.el, artcl.la],
			sentences: [
				{
					id: 1,
					sentence: "The man has that",
					translation: "EL man has ESO",
					data: [
						{ word: "The", translation: artcl.el },
						{ word: "man" },
						{ word: "has" },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 2,
					sentence: "The guy went to the house",
					translation: "EL guy went A the house",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "guy" },
						{ word: "went" },
						{ word: "to", translation: prep.a },
						{ word: "the" },
						{ word: "house" },
					],
				},
				{
					id: 3,
					sentence: "That is the girl's",
					translation: "ESO is DE LA girl",
					data: [
						{ word: "that", translation: pron.eso },
						{ word: "is" },
						{ word: "from", translation: prep.de },
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
					],
				},
				{
					id: 4,
					sentence: "You couldn't come from there",
					translation: "YOU NO could come DE there",
					data: [
						{ word: "you" },
						{
							phrase: "couldn't come",
							translation: advrb.no,
							phraseTranslation: "NO could come",
						},
						{ word: "from", translation: prep.de },
						{ word: "there" },
					],
				},
				{
					id: 5,
					sentence: "The boy didn't see us.",
					translation: "EL boy NO saw us",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "boy" },
						{
							phrase: "didn't see",
							translation: advrb.no,
							phraseTranslation: "NO saw",
						},
						{ word: "us" },
					],
				},
				{
					id: 6,
					sentence: "The man can't have the girl's things",
					translation: "EL man NO can have the things DE LA girl",
					data: [
						{ word: "The", translation: artcl.el },
						{ word: "man" },
						{
							phrase: "can't have",
							translation: advrb.no,
							phraseTranslation: "NO can have",
						},
						{ word: "the" },
						{ word: "things" },
						{ word: "from", translation: prep.de },
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
						,
					],
				},
				{
					id: 7,
					sentence: "The man and the woman wouldn't go there",
					translation: "EL man Y LA woman NO would go there",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "man" },
						{ word: "and", translation: conj.y },
						{ word: "the", translation: artcl.LA },
						{ word: "woman" },
						{
							phrase: "wouldn't go",
							translation: advrb.no,
							phraseTranslation: "NO would go",
						},
						{ word: "there" },
					],
				},
				{
					id: 8,
					sentence: "The guy told the girl it was a plastic cup",
					translation: "EL guy told LA girl QUE it was a cup DE plastic",
					data: [
						{ word: "The", translation: artcl.el },
						{ word: "guy" },
						{ word: "told" },
						{
							phrase: "the girl",
							translation: conj.que,
							phraseTranslation: "LA girl QUE",
						},
						{ word: "it" },
						{ word: "was" },
						{ word: "a" },
						{
							word: "plastic cup",
							translation: prep.de,
							phraseTranslation: "cup DE plastic",
						},
					],
				},
				{
					id: 9,
					sentence: "The lady and I told her it was OK",
					translation: "LA lady Y I told her QUE it was OK",
					data: [
						{ word: "the", translation: artcl.la },
						{ word: "lady" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{ word: "told" },
						{ phrase: "her" },
						{
							phrase: "it was OK",
							translation: conj.que,
							phraseTranslation: "QUE it was OK",
						},
					],
				},
				{
					id: 10,
					sentence: "The girl won't say that I did it",
					translation: "LA girl NO will say QUE I did it",
					data: [
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
						{
							phrase: "won't say",
							translation: advrb.no,
							phraseTranslation: "NO will say",
						},
						{ word: "that", tranlation: conj.que },
						{ word: "I" },
						{ word: "did" },
						{ word: "it" },
					],
				},
			],
		},
		7: {
			lesson: 7,
			name: "Lesson 7",
			details: "Direct Objects: LO, LA. ",
			info: [
				"How does HIM/HER fit in as far as Word Categories go, like nouns and verbs? It can't always be subsituted in place of other nouns: 'Food makes me happy.' != 'Him makes me happy' ",
				"HE and HIM have to go in very different and specific places in sentences, one is the subject (HE), and one is the Direct Object (HIM) ",
				dObj.info[0],
				dObj.info[1],
				dObj.info[2],
				"The Spanish Direct Objects for HIM and HER are LO and LA!",
				"This LA(her) is diffrent then the LA for THE! If LA occurs before a noun it has to mean THE, if it occurs before a verb it has to mean HER!",
				dObj.info[3],
			],
			wordBank: [dObj.lo, dObj.la],
			sentences: [
				{
					id: 1,
					sentence: "Our friends see her",
					translation: "Our friends LA see",
					data: [
						{ word: "Our" },
						{ word: "friends" },
						{
							word: "see her",
							translation: dObj.la,
							phraseTranslation: "LA see",
						},
					],
				},
				{
					id: 2,
					sentence: "We found it",
					translation: "We LO found",
					data: [
						{ word: "We" },
						{
							phrase: "found it",
							translation: dObj.lo,
							phraseTranslation: "LO found",
						},
					],
				},
				{
					id: 3,
					sentence: "He loves it and calls it his own",
					translation: "He LO loves Y LO calls his own",
					data: [
						{ word: "He" },
						{
							phrase: "loves it",
							translation: dObj.lo,
							phraseTranslation: "LO loves",
						},
						{ word: "and", translation: conj.y },
						{
							phrase: "calls it",
							translation: dObj.lo,
							phraseTranslation: "LO calls",
						},
						{ word: "his own" },
					],
				},
				{
					id: 4,
					sentence: "She and I did it",
					translation: "She Y I LO did",
					data: [
						{ word: "She" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{
							phrase: "did it",
							translation: dObj.lo,
							phraseTranslation: "LO did",
						},
					],
				},
				{
					id: 5,
					sentence: "That caused it",
					translation: "ESO LO caused",
					data: [
						{ word: "That", translation: pron.eso },
						{
							phrase: "caused it",
							translation: dObj.lo,
							phraseTranslation: "LO caused",
						},
					],
				},
				{
					id: 6,
					sentence: "The girl doesn't love him",
					translation: "LA girl NO LO loves",
					reference: { no: [advrb.no.info[7]] },
					data: [
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
						{
							phrase: "doesn't love him",
							translation: [advrb.no, dObj.lo],
							phraseTranslation: "NO LO loves",
							reference: { no: [advrb.no.info[7]] },
						},
					],
				},
				{
					id: 7,
					sentence: "That went to it's home",
					translation: "ESO went A its home",
					data: [
						{ word: "That", translation: pron.eso },
						{ word: "went" },
						{ word: "to", translation: prep.a },
						{ word: "its" },
						{ word: "home" },
					],
				},
				{
					id: 8,
					sentence: "I don't take her to school",
					translation: "I NO LA take A school",
					data: [
						{ word: "I" },
						{
							phrase: "don't take her",
							translation: [advrb.no, dObj.la],
						},
						{ word: "to", translation: prep.a },
						{ word: "school" },
					],
				},
				{
					id: 9,
					sentence: "That didn't hurt her",
					translation: "ESO NO LA hurt",
					reference: { no: [advrb.no.info[7]] },
					data: [
						{ word: "That", translation: pron.eso },
						{
							phrase: "didn't hurt her",
							translation: [advrb.no, dObj.la],
							phraseTranslation: "NO LA hurt",
							reference: { no: [advrb.no.info[7]] },
						},
					],
				},
				{
					id: 10,
					sentence: "The man found her with a rag doll",
					translation: "EL man LA found with a doll DE rag",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "man" },
						{
							phrase: "found her",
							translation: dObj.la,
							phraseTranslation: "LA found",
						},
						{ word: "with" },
						{ word: "a" },
						{
							phrase: "rag doll",
							translation: prep.de,
							phraseTranslation: "doll DE rag",
						},
					],
				},
				{
					id: 11,
					sentence: "The boy is not the same one",
					translation: "EL boy NO is EL same one",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "boy" },
						{
							phrase: "is not",
							translation: [advrb.no, dObj.lo],
							phraseTranslation: "NO is",
						},
						{ word: "the", translation: artcl.el },
						{ word: "same" },
						{ word: "one" },
					],
				},
				{
					id: 12,
					sentence: "I think the girl saw him",
					translation: "I think QUE LA girl LO saw",
					data: [
						{
							word: "I think",
							translation: conj.que,
							phraseTranslation: "I think QUE",
						},
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
						{
							phrase: "saw him",
							translation: dObj.lo,
							phraseTranslation: "LO saw",
						},
					],
				},
				{
					id: 13,
					sentence: "My dog saw her coming from the store",
					translation: "My dog LA saw coming DE the store",
					data: [
						{ word: "My" },
						{ word: "dog" },
						{
							phrase: "saw her",
							translation: dObj.la,
							phraseTranslation: "LA saw",
						},
						{ word: "coming" },
						{ word: "from", translation: prep.de },
						{ word: "the" },
						{ word: "store" },
					],
				},
				{
					id: 14,
					sentence: "I think that that is from Canada",
					translation: "I think QUE ESO is DE Canada",
					data: [
						{
							phrase: "I think that",
							translation: conj.que,
							phraseTranslation: "I think QUE",
						},
						{ word: "that", translation: pron.eso },
						{ word: "is" },
						{ word: "from", translation: prep.de },
						{ word: "Canada" },
					],
				},
				{
					id: 15,
					sentence: "The girl from your country did that",
					translation: "LA girl DE your country did ESO",
					data: [
						{ word: "the", translation: artcl.la },
						{ word: "girl" },
						{ word: "from", translation: prep.de },
						{ word: "your" },
						{ word: "country" },
						{ word: "did" },
						{ word: "that", translation: pron.eso },
					],
				},
				{
					id: 16,
					sentence: "The man and the woman see her",
					translation: "EL man Y LA woman LA see",
					data: [
						{ word: "the", translation: artcl.el },
						{ word: "man" },
						{ word: "and", translation: conj.y },
						{ word: "the", translation: artcl.la },
						{ word: "woman" },
						{
							phrase: "see her",
							translation: dObj.la,
							phraseTranslation: "LA see",
						},
					],
				},
				{
					id: 17,
					sentence: "The mother didn't find him",
					translation: "LA mother NO LO found",
					data: [
						{ word: "the", translation: artcl.la },
						{ word: "mother" },
						{
							phrase: "didn't find him",
							translation: [advrb.no, dObj.lo],
							phraseTranslation: "NO LO found",
						},
					],
				},
				{
					id: 18,
					sentence: "Sara's music drifted to his ears",
					translation: "The music DE Sara drifted A his ears",
					data: [
						{ word: "The" },
						{ word: "music" },
						{ word: "DE", translation: prep.de },
						{ word: "Sara" },
						{ word: "drifted" },
						{ word: "A", translation: prep.a },
						{ word: "his" },
						{ word: "ears" },
					],
				},
				{
					id: 19,
					sentence: "She and I chased a bird and it flew away from us",
					translation: "She Y I chased a bird Y it flew away DE us",
					data: [
						{ word: "She" },
						{ word: "and", translation: conj.y },
						{ word: "I" },
						{ word: "chased a bird" },
						{ word: "and", translation: conj.y },
						{ word: "it flew away" },
						{ word: "from", translation: prep.de },
						{ word: "us" },
					],
				},
				{
					id: 20,
					sentence: "They said he told them he had gone to the party",
					translation: "They said QUE he told them QUE he had gone A the party",
					data: [
						{
							word: "They said",
							translation: conj.que,
							phraseTranslation: "They said QUE",
						},
						{
							word: "he told them",
							translation: conj.que,
							phraseTranslation: "he told them QUE",
						},
						{ word: "he had gone" },
						{ word: "to", translation: prep.a },
						{ word: "the party" },
					],
				},
			],
		},
	},
}

export default spanishData
