import localFont from "next/font/local"
import "./globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer"

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
})
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
})

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`layoutBody ${geistSans.variable} ${geistMono.variable} antialiased bg-primary_light h-screen flex flex-col`}
			>
				<div className="flex flex-col justify-between h-full">
					<Header />
					{children}

					<Footer />
				</div>
			</body>
		</html>
	)
}
